### ISSUE TITLE
unable to get the device video on controller

### ISSUE THREAD

**Issue by sai-tirunagiri** [nanoscopic/ios_remote_provider#2]
Hi,

I have done the setup and the vidtest2 app is installed on the device but I am unable to launch the app, after booting up the provide I see some warn logs as below.

```
WARN[0020] Process end - wda                             proc=wda type=proc_end
Notified control floor of 'wda stop'; uuid=***9e73
INFO[0021] Process start - wda                           binary=xcodebuild proc=wda testrun=bin/wda/WebDriverAgentRunner_iphoneos14.4-arm64-armv7.xctestrun type=proc_start
WARN[0022] Process end - wda                             proc=wda type=proc_end
Notified control floor of 'wda stop'; uuid=***4bbe
Got connection to port
INFO[0024] Socket dial error                             err="read tcp 127.0.0.1:51088->127.0.0.1:8110: read: connection reset by peer" spec="tcp://127.0.0.1:8110" type=err_socket_dial
Got connection to port
INFO[0025] Socket dial error                             err="read tcp 127.0.0.1:51090->127.0.0.1:8104: read: connection reset by peer" spec="tcp://127.0.0.1:8104" type=err_socket_dial
INFO[0025] Process start - wda                           binary=xcodebuild proc=wda testrun=bin/wda/WebDriverAgentRunner_iphoneos14.4-arm64-armv7.xctestrun type=proc_start
INFO[0025] Process start - wda                           binary=xcodebuild proc=wda testrun=bin/wda/WebDriverAgentRunner_iphoneos14.4-arm64-armv7.xctestrun type=proc_start
WARN[0027] Process end - wda                             proc=wda type=proc_end
Notified control floor of 'wda stop'; uuid=***3a67
WARN[0027] Process end - wda                             proc=wda type=proc_end
Notified control floor of 'wda stop'; uuid=***9e73
Got connection to port
INFO[0029] Socket dial error                             err="read tcp 127.0.0.1:51094->127.0.0.1:8107: read: connection reset by peer" spec="tcp://127.0.0.1:8107" type=err_socket_dial
INFO[0032] Process start - wda                           binary=xcodebuild proc=wda testrun=bin/wda/WebDriverAgentRunner_iphoneos14.4-arm64-armv7.xctestrun type=proc_start
WARN[0034] Process end - wda                             proc=wda type=proc_end
Notified control floor of 'wda stop'; uuid=***4bbe
Got connection to port
INFO[0034] Socket dial error                             err="read tcp 127.0.0.1:51098->127.0.0.1:8110: read: connection reset by peer" spec="tcp://127.0.0.1:8110" type=err_socket_dial
Got connection to port
INFO[0035] Socket dial error                             err="read tcp 127.0.0.1:51100->127.0.0.1:8104: read: connection reset by peer" spec="tcp://127.0.0.1:8104" type=err_socket_dial
INFO[0037] Process start - wda                           binary=xcodebuild proc=wda testrun=bin/wda/WebDriverAgentRunner_iphoneos14.4-arm64-armv7.xctestrun type=proc_start
INFO[0037] Process start - wda                           binary=xcodebuild proc=wda testrun=bin/wda/WebDriverAgentRunner_iphoneos14.4-arm64-armv7.xctestrun type=proc_start
WARN[0038] Process end - wda                             proc=wda type=proc_end
Notified control floor of 'wda stop'; uuid=***3a67
WARN[0039] Process end - wda                             proc=wda type=proc_end
Notified control floor of 'wda stop'; uuid=***9e73
Got connection to port
INFO[0040] Socket dial error                             err="read tcp 127.0.0.1:51104->127.0.0.1:8107: read: connection reset by peer" spec="tcp://127.0.0.1:8107" type=err_socket_dial
```

And on the controlfloor logs I see below,
```
WDA stopped for UDID
provider user=first
devStatus request; status=wdaStopped
  udid=UDID
WDA stopped for UDID
sending {id:5539,type:"ping"}

received {id:5539,text:"pong"}

pong text pong
provider user=first
devStatus request; status=wdaStopped
  udid=UDID
WDA stopped for UDID
sending {id:32060,type:"ping"}

received {id:32060,text:"pong"}

pong text pong
provider user=first
devStatus request; status=wdaStopped
  udid=UDID
WDA stopped for UDID
provider user=first
devStatus request; status=wdaStopped
  udid=UDID
WDA stopped for UDID
sending {id:20462,type:"ping"}

received {id:20462,text:"pong"}
```

Could someone please guide me, if I am missing any setup instruction?

Thanks

**Comment by nanoscopic** [comment]
WDA is not starting on your device / appears to be crashing on start. Hence "process end - wda".

I'd recommend pulling / using the latest updates I just made today. The updates add a `make wda` command that will build a properly signed WDA for you.

To ensure WDA is built correctly and can work on your device, you'll need to do/have done all of the following:
1. Create an identifier in Apple Developer website that matches your chosen bundle ID to use for WDA.
2. Create a provisioning profile in Apple Developer website that contains your Mac used to run WDA and also the iOS devices you intend to use WDA on. ( and the identifier you made of course )
3. Login to Xcode on your mac
4. Add your Apple Developer Team OU to config.json
5. Run `make wda`

If your provisioning profile is not chosen automatically / the above still does not work, you can update config.json to specify "Manual" buildStyle for runner, and place the name of your created provisioning profile in runner.provisioningProfile in config.json , run `make wdaclean` then `make wda` and try to run provider again.

**Comment by sai-tirunagiri** [comment]
I tried the above steps, seems like I am still running into the same issue even after building the wda.

controlfloor logs
```
Provider login user=first pass=2e9dda41152c796a245b7b6c027b4589
provider login ok
provider user=first
got ws connection
provider user=first
devStatus request; status=exists
  udid=5126be31cfff436356a1627c09c9268136513a67
Notified that device 5126be31cfff436356a1627c09c9268136513a67 exists
Adding device:
  udid:5126be31cfff436356a1627c09c9268136513a67
  name:unknown
  clickWidth:375
  clickHegiht:667
Device with udid 5126be31cfff436356a1627c09c9268136513a67 already existed
provider user=first
devStatus request; status=info
  udid=5126be31cfff436356a1627c09c9268136513a67
Device info for 5126be31cfff436356a1627c09c9268136513a67:
{"InternationalMobileEquipmentIdentity":"356642080408965","DeviceName":"Ameet’s iPhone","EthernetAddress":"78:67:d7:09:ef:fa","ModelNumber":"MN8X2","HardwareModel":"D101AP","ProductType":"iPhone9,3","ProductVersion":"14.4","UniqueDeviceID":"5126be31cfff436356a1627c09c9268136513a67",}
provider user=first
devStatus request; status=wdaStopped
  udid=5126be31cfff436356a1627c09c9268136513a67
WDA stopped for 5126be31cfff436356a1627c09c9268136513a67
provider user=first
devStatus request; status=exists
  udid=ada3ad8097e58c7eea8c1821640ccd4cda484bbe
Notified that device ada3ad8097e58c7eea8c1821640ccd4cda484bbe exists
Adding device:
  udid:ada3ad8097e58c7eea8c1821640ccd4cda484bbe
  name:unknown
  clickWidth:375
  clickHegiht:667
Device with udid ada3ad8097e58c7eea8c1821640ccd4cda484bbe already existed
provider user=first
devStatus request; status=info
  udid=ada3ad8097e58c7eea8c1821640ccd4cda484bbe
Device info for ada3ad8097e58c7eea8c1821640ccd4cda484bbe:
{"DeviceName":"Ameet’s iPhone","EthernetAddress":"78:67:d7:09:ef:fa","ModelNumber":"MN8X2","HardwareModel":"D101AP","ProductType":"iPhone9,3","ProductVersion":"14.4","UniqueDeviceID":"5126be31cfff436356a1627c09c9268136513a67","InternationalMobileEquipmentIdentity":"356642080408965",}
sending {id:21132,type:"ping"}

received {id:21132,text:"pong"}

pong text pong
provider user=first
devStatus request; status=wdaStopped
  udid=5126be31cfff436356a1627c09c9268136513a67
WDA stopped for 5126be31cfff436356a1627c09c9268136513a67
provider user=first
devStatus request; status=wdaStopped
  udid=5126be31cfff436356a1627c09c9268136513a67
WDA stopped for 5126be31cfff436356a1627c09c9268136513a67
provider user=first
devStatus request; status=wdaStopped
  udid=ada3ad8097e58c7eea8c1821640ccd4cda484bbe
WDA stopped for ada3ad8097e58c7eea8c1821640ccd4cda484bbe
provider user=first
devStatus request; status=exists
  udid=bd8f3d57554c6fcd2914ad39a0de2ddebd919e73
Notified that device bd8f3d57554c6fcd2914ad39a0de2ddebd919e73 exists
Adding device:
  udid:bd8f3d57554c6fcd2914ad39a0de2ddebd919e73
  name:unknown
  clickWidth:375
  clickHegiht:667
Device with udid bd8f3d57554c6fcd2914ad39a0de2ddebd919e73 already existed
provider user=first
devStatus request; status=info
  udid=bd8f3d57554c6fcd2914ad39a0de2ddebd919e73
Device info for bd8f3d57554c6fcd2914ad39a0de2ddebd919e73:
{"DeviceName":"Ameet’s iPhone","EthernetAddress":"78:67:d7:09:ef:fa","ModelNumber":"MN8X2","HardwareModel":"D101AP","ProductType":"iPhone9,3","ProductVersion":"14.4","UniqueDeviceID":"5126be31cfff436356a1627c09c9268136513a67","InternationalMobileEquipmentIdentity":"356642080408965",}
sending {id:27758,type:"ping"}

received {id:27758,text:"pong"}

pong text pong
provider user=first
devStatus request; status=wdaStopped
  udid=ada3ad8097e58c7eea8c1821640ccd4cda484bbe
WDA stopped for ada3ad8097e58c7eea8c1821640ccd4cda484bbe
provider user=first
devStatus request; status=wdaStopped
  udid=bd8f3d57554c6fcd2914ad39a0de2ddebd919e73
WDA stopped for bd8f3d57554c6fcd2914ad39a0de2ddebd919e73
provider user=first
devStatus request; status=wdaStopped
  udid=5126be31cfff436356a1627c09c9268136513a67
WDA stopped for 5126be31cfff436356a1627c09c9268136513a67
provider user=first
devStatus request; status=wdaStopped
  udid=ada3ad8097e58c7eea8c1821640ccd4cda484bbe
WDA stopped for ada3ad8097e58c7eea8c1821640ccd4cda484bbe
provider user=first
devStatus request; status=wdaStopped
  udid=bd8f3d57554c6fcd2914ad39a0de2ddebd919e73
WDA stopped for bd8f3d57554c6fcd2914ad39a0de2ddebd919e73
sending {id:19508,type:"ping"}

received {id:19508,text:"pong"}

pong text pong
provider user=first
devStatus request; status=wdaStopped
  udid=bd8f3d57554c6fcd2914ad39a0de2ddebd919e73
WDA stopped for bd8f3d57554c6fcd2914ad39a0de2ddebd919e73
sending {id:21740,type:"ping"}

received {id:21740,text:"pong"}

pong text pong
provider user=first
devStatus request; status=wdaStopped
  udid=ada3ad8097e58c7eea8c1821640ccd4cda484bbe
WDA stopped for ada3ad8097e58c7eea8c1821640ccd4cda484bbe
sending {id:19367,type:"ping"}

received {id:19367,text:"pong"}

pong text pong
provider user=first
devStatus request; status=wdaStopped
  udid=5126be31cfff436356a1627c09c9268136513a67
WDA stopped for 5126be31cfff436356a1627c09c9268136513a67
provider user=first
devStatus request; status=wdaStopped
  udid=bd8f3d57554c6fcd2914ad39a0de2ddebd919e73
WDA stopped for bd8f3d57554c6fcd2914ad39a0de2ddebd919e73
sending {id:24844,type:"ping"}

received {id:24844,text:"pong"}
```

provider logs
```
(base) mac-mini-1:ios_remote_provider blr-cauvery$ ./main
{
  "bin_paths":{
    iosif:"bin/iosif"
  }
  repos:{
    iosif:"https://github.com/nanoscopic/iosif.git"
    vidapp:"https://github.com/nanoscopic/ios_video_app.git"
    wda:"https://github.com/appium/WebDriverAgent.git"
    ujsonin:"https://github.com/nanoscopic/ujsonin.git"
    pbxproj:"https://github.com/kronenthaler/mod-pbxproj"
  }
  wda:{
    devTeamOu:"SCW573G2GF"
    lib:{
      buildStyle:"Automatic"
      provisioningProfile:""
    }
    runner:{
      buildStyle:"Manual"
      provisioningProfile:"Provision Profile Manual"
    }
    bundleIdPrefix:"com.appium"
  }
  wdaXctestRunFolder:"repos/WebDriverAgent/build/Build/Products"
  port:8027
  controlfloor:{
    username:"first"
    host:"127.0.0.1:8080"
  }
}WARN[0000] Leftover iosif - Sending SIGTERM              pid=79207 proc=iosif type=proc_cleanup
Location from redirect of controlfloor login:'http://127.0.0.1:8080/provider/'
Logged in to control floor
INFO[0001] Process start - device_trigger                binary=bin/iosif proc=device_trigger type=proc_start
Creating IIFDev with udid=5126be31cfff436356a1627c09c9268136513a67
udid: 5126be31cfff436356a1627c09c9268136513a67
Running bin/iosif [mg -json -id 5126be31cfff436356a1627c09c9268136513a67 main-screen-width main-screen-height main-screen-scale]
json:{
"main-screen-width":750,
"main-screen-height":1334,
"main-screen-scale":2
}

Notified control floor of 'device existence'; uuid=***3a67
udid for info: 5126be31cfff436356a1627c09c9268136513a67
json:{
DeviceName:"Ameet’s iPhone",
EthernetAddress:"78:67:d7:09:ef:fa",
ModelNumber:"MN8X2",
HardwareModel:"D101AP",
ProductType:"iPhone9,3",
ProductVersion:"14.4",
UniqueDeviceID:"5126be31cfff436356a1627c09c9268136513a67",
InternationalMobileEquipmentIdentity:"356642080408965",
}

mapped result:map[DeviceName:Ameet’s iPhone EthernetAddress:78:67:d7:09:ef:fa HardwareModel:D101AP InternationalMobileEquipmentIdentity:356642080408965 ModelNumber:MN8X2 ProductType:iPhone9,3 ProductVersion:14.4 UniqueDeviceID:5126be31cfff436356a1627c09c9268136513a67]
INFO[0001] Device Info                                   info="map[DeviceName:Ameet’s iPhone EthernetAddress:78:67:d7:09:ef:fa HardwareModel:D101AP InternationalMobileEquipmentIdentity:356642080408965 ModelNumber:MN8X2 ProductType:iPhone9,3 ProductVersion:14.4 UniqueDeviceID:5126be31cfff436356a1627c09c9268136513a67]" type=devInfo uuid="***3a67"
Notified control floor of 'device info'; uuid=***3a67
INFO[0001] Socket dial error                             err="dial tcp 127.0.0.1:8912: connect: connection refused" spec="tcp://127.0.0.1:8912" type=err_socket_dial
Tunnel from 8102 to 8100
Starting bin/iosif with [tunnel -id 5126be31cfff436356a1627c09c9268136513a67 8102:8100]
Tunnel from 8102 to 8100
failed to bind to 8102
Tunnel stopped
Found file repos/WebDriverAgent/build/Build/Products
Found file repos/WebDriverAgent/build/Build/Products/WebDriverAgentRunner_iphoneos14.4-arm64-armv7.xctestrun
testrun = repos/WebDriverAgent/build/Build/Products/WebDriverAgentRunner_iphoneos14.4-arm64-armv7.xctestrun
Tunnel from 8103 to 8352
Tunnel from 8104 to 8351
Starting bin/iosif with [tunnel -id 5126be31cfff436356a1627c09c9268136513a67 8103:8352 8104:8351]
INFO[0003] Process start - wda                           binary=xcodebuild proc=wda testrun=repos/WebDriverAgent/build/Build/Products/WebDriverAgentRunner_iphoneos14.4-arm64-armv7.xctestrun type=proc_start
Tunnel from 8103 to 8352
bound to port 8103
Tunnel from 8104 to 8351
bound to port 8104
WARN[0005] Process end - wda                             proc=wda type=proc_end
INFO[0005] Process start - wda                           binary=xcodebuild proc=wda testrun=repos/WebDriverAgent/build/Build/Products/WebDriverAgentRunner_iphoneos14.4-arm64-armv7.xctestrun type=proc_start
Notified control floor of 'wda stop'; uuid=***3a67
Creating IIFDev with udid=ada3ad8097e58c7eea8c1821640ccd4cda484bbe
udid: ada3ad8097e58c7eea8c1821640ccd4cda484bbe
Running bin/iosif [mg -json -id ada3ad8097e58c7eea8c1821640ccd4cda484bbe main-screen-width main-screen-height main-screen-scale]
Got connection to port
INFO[0005] Socket dial error                             err="read tcp 127.0.0.1:58620->127.0.0.1:8104: read: connection reset by peer" spec="tcp://127.0.0.1:8104" type=err_socket_dial
json:{
"main-screen-width":750,
"main-screen-height":1334,
"main-screen-scale":2
}

Notified control floor of 'device existence'; uuid=***4bbe
udid for info: ada3ad8097e58c7eea8c1821640ccd4cda484bbe
json:{
DeviceName:"Ameet’s iPhone",
EthernetAddress:"78:67:d7:09:ef:fa",
ModelNumber:"MN8X2",
HardwareModel:"D101AP",
ProductType:"iPhone9,3",
ProductVersion:"14.4",
UniqueDeviceID:"5126be31cfff436356a1627c09c9268136513a67",
InternationalMobileEquipmentIdentity:"356642080408965",
}

mapped result:map[DeviceName:Ameet’s iPhone EthernetAddress:78:67:d7:09:ef:fa HardwareModel:D101AP InternationalMobileEquipmentIdentity:356642080408965 ModelNumber:MN8X2 ProductType:iPhone9,3 ProductVersion:14.4 UniqueDeviceID:5126be31cfff436356a1627c09c9268136513a67]
INFO[0006] Device Info                                   info="map[DeviceName:Ameet’s iPhone EthernetAddress:78:67:d7:09:ef:fa HardwareModel:D101AP InternationalMobileEquipmentIdentity:356642080408965 ModelNumber:MN8X2 ProductType:iPhone9,3 ProductVersion:14.4 UniqueDeviceID:5126be31cfff436356a1627c09c9268136513a67]" type=devInfo uuid="***4bbe"
Notified control floor of 'device info'; uuid=***4bbe
INFO[0006] Socket dial error                             err="dial tcp 127.0.0.1:8912: connect: connection refused" spec="tcp://127.0.0.1:8912" type=err_socket_dial
Tunnel from 8105 to 8100
Starting bin/iosif with [tunnel -id ada3ad8097e58c7eea8c1821640ccd4cda484bbe 8105:8100]
Tunnel from 8105 to 8100
bound to port 8105
WARN[0006] Process end - wda                             proc=wda type=proc_end
Notified control floor of 'wda stop'; uuid=***3a67
Found file repos/WebDriverAgent/build/Build/Products
Found file repos/WebDriverAgent/build/Build/Products/WebDriverAgentRunner_iphoneos14.4-arm64-armv7.xctestrun
testrun = repos/WebDriverAgent/build/Build/Products/WebDriverAgentRunner_iphoneos14.4-arm64-armv7.xctestrun
Tunnel from 8106 to 8352
Tunnel from 8107 to 8351
Starting bin/iosif with [tunnel -id ada3ad8097e58c7eea8c1821640ccd4cda484bbe 8106:8352 8107:8351]
INFO[0008] Process start - wda                           binary=xcodebuild proc=wda testrun=repos/WebDriverAgent/build/Build/Products/WebDriverAgentRunner_iphoneos14.4-arm64-armv7.xctestrun type=proc_start
Tunnel from 8106 to 8352
bound to port 8106
Tunnel from 8107 to 8351
bound to port 8107
INFO[0008] Process start - wda                           binary=xcodebuild proc=wda testrun=repos/WebDriverAgent/build/Build/Products/WebDriverAgentRunner_iphoneos14.4-arm64-armv7.xctestrun type=proc_start
WARN[0009] Process end - wda                             proc=wda type=proc_end
Notified control floor of 'wda stop'; uuid=***3a67
WARN[0009] Process end - wda                             proc=wda type=proc_end
INFO[0009] Process start - wda                           binary=xcodebuild proc=wda testrun=repos/WebDriverAgent/build/Build/Products/WebDriverAgentRunner_iphoneos14.4-arm64-armv7.xctestrun type=proc_start
Notified control floor of 'wda stop'; uuid=***4bbe
Creating IIFDev with udid=bd8f3d57554c6fcd2914ad39a0de2ddebd919e73
udid: bd8f3d57554c6fcd2914ad39a0de2ddebd919e73
Running bin/iosif [mg -json -id bd8f3d57554c6fcd2914ad39a0de2ddebd919e73 main-screen-width main-screen-height main-screen-scale]
Got connection to port
INFO[0010] Socket dial error                             err="read tcp 127.0.0.1:58630->127.0.0.1:8107: read: connection reset by peer" spec="tcp://127.0.0.1:8107" type=err_socket_dial
json:{
"main-screen-width":750,
"main-screen-height":1334,
"main-screen-scale":2
}

Notified control floor of 'device existence'; uuid=***9e73
udid for info: bd8f3d57554c6fcd2914ad39a0de2ddebd919e73
json:{
DeviceName:"Ameet’s iPhone",
EthernetAddress:"78:67:d7:09:ef:fa",
ModelNumber:"MN8X2",
HardwareModel:"D101AP",
ProductType:"iPhone9,3",
ProductVersion:"14.4",
UniqueDeviceID:"5126be31cfff436356a1627c09c9268136513a67",
InternationalMobileEquipmentIdentity:"356642080408965",
}

mapped result:map[DeviceName:Ameet’s iPhone EthernetAddress:78:67:d7:09:ef:fa HardwareModel:D101AP InternationalMobileEquipmentIdentity:356642080408965 ModelNumber:MN8X2 ProductType:iPhone9,3 ProductVersion:14.4 UniqueDeviceID:5126be31cfff436356a1627c09c9268136513a67]
INFO[0010] Device Info                                   info="map[DeviceName:Ameet’s iPhone EthernetAddress:78:67:d7:09:ef:fa HardwareModel:D101AP InternationalMobileEquipmentIdentity:356642080408965 ModelNumber:MN8X2 ProductType:iPhone9,3 ProductVersion:14.4 UniqueDeviceID:5126be31cfff436356a1627c09c9268136513a67]" type=devInfo uuid="***9e73"
Notified control floor of 'device info'; uuid=***9e73
INFO[0010] Socket dial error                             err="dial tcp 127.0.0.1:8912: connect: connection refused" spec="tcp://127.0.0.1:8912" type=err_socket_dial
Tunnel from 8108 to 8100
Starting bin/iosif with [tunnel -id bd8f3d57554c6fcd2914ad39a0de2ddebd919e73 8108:8100]
Tunnel from 8108 to 8100
bound to port 8108
Found file repos/WebDriverAgent/build/Build/Products
Found file repos/WebDriverAgent/build/Build/Products/WebDriverAgentRunner_iphoneos14.4-arm64-armv7.xctestrun
testrun = repos/WebDriverAgent/build/Build/Products/WebDriverAgentRunner_iphoneos14.4-arm64-armv7.xctestrun
Tunnel from 8109 to 8352
Tunnel from 8110 to 8351
Starting bin/iosif with [tunnel -id bd8f3d57554c6fcd2914ad39a0de2ddebd919e73 8109:8352 8110:8351]
INFO[0012] Process start - wda                           binary=xcodebuild proc=wda testrun=repos/WebDriverAgent/build/Build/Products/WebDriverAgentRunner_iphoneos14.4-arm64-armv7.xctestrun type=proc_start
WARN[0012] Process end - wda                             proc=wda type=proc_end
Notified control floor of 'wda stop'; uuid=***4bbe
Tunnel from 8109 to 8352
bound to port 8109
Tunnel from 8110 to 8351
bound to port 8110
WARN[0013] Process end - wda                             proc=wda type=proc_end
INFO[0013] Process start - wda                           binary=xcodebuild proc=wda testrun=repos/WebDriverAgent/build/Build/Products/WebDriverAgentRunner_iphoneos14.4-arm64-armv7.xctestrun type=proc_start
Notified control floor of 'wda stop'; uuid=***9e73
Got connection to port
INFO[0014] Socket dial error                             err="read tcp 127.0.0.1:58639->127.0.0.1:8110: read: connection reset by peer" spec="tcp://127.0.0.1:8110" type=err_socket_dial
INFO[0014] Process start - wda                           binary=xcodebuild proc=wda testrun=repos/WebDriverAgent/build/Build/Products/WebDriverAgentRunner_iphoneos14.4-arm64-armv7.xctestrun type=proc_start
INFO[0014] Process start - wda                           binary=xcodebuild proc=wda testrun=repos/WebDriverAgent/build/Build/Products/WebDriverAgentRunner_iphoneos14.4-arm64-armv7.xctestrun type=proc_start
Got connection to port
INFO[0015] Socket dial error                             err="read tcp 127.0.0.1:58640->127.0.0.1:8104: read: connection reset by peer" spec="tcp://127.0.0.1:8104" type=err_socket_dial
WARN[0015] Process end - wda                             proc=wda type=proc_end
Notified control floor of 'wda stop'; uuid=***3a67
WARN[0015] Process end - wda                             proc=wda type=proc_end
Notified control floor of 'wda stop'; uuid=***4bbe
WARN[0015] Process end - wda                             proc=wda type=proc_end
Notified control floor of 'wda stop'; uuid=***9e73
INFO[0017] Process start - wda                           binary=xcodebuild proc=wda testrun=repos/WebDriverAgent/build/Build/Products/WebDriverAgentRunner_iphoneos14.4-arm64-armv7.xctestrun type=proc_start
Got connection to port
INFO[0020] Socket dial error                             err="read tcp 127.0.0.1:58647->127.0.0.1:8107: read: connection reset by peer" spec="tcp://127.0.0.1:8107" type=err_socket_dial
WARN[0020] Process end - wda                             proc=wda type=proc_end
Notified control floor of 'wda stop'; uuid=***9e73
INFO[0020] Process start - wda                           binary=xcodebuild proc=wda testrun=repos/WebDriverAgent/build/Build/Products/WebDriverAgentRunner_iphoneos14.4-arm64-armv7.xctestrun type=proc_start
WARN[0022] Process end - wda                             proc=wda type=proc_end
Notified control floor of 'wda stop'; uuid=***4bbe
Got connection to port
INFO[0024] Socket dial error                             err="read tcp 127.0.0.1:58653->127.0.0.1:8110: read: connection reset by peer" spec="tcp://127.0.0.1:8110" type=err_socket_dial
INFO[0025] Process start - wda                           binary=xcodebuild proc=wda testrun=repos/WebDriverAgent/build/Build/Products/WebDriverAgentRunner_iphoneos14.4-arm64-armv7.xctestrun type=proc_start
Got connection to port
INFO[0025] Socket dial error                             err="read tcp 127.0.0.1:58654->127.0.0.1:8104: read: connection reset by peer" spec="tcp://127.0.0.1:8104" type=err_socket_dial
INFO[0025] Process start - wda                           binary=xcodebuild proc=wda testrun=repos/WebDriverAgent/build/Build/Products/WebDriverAgentRunner_iphoneos14.4-arm64-armv7.xctestrun type=proc_start
WARN[0026] Process end - wda                             proc=wda type=proc_end
Notified control floor of 'wda stop'; uuid=***3a67
WARN[0027] Process end - wda                             proc=wda type=proc_end
Notified control floor of 'wda stop'; uuid=***9e73
Got connection to port
```

**Comment by nanoscopic** [comment]
@sai-tirunagiri You may wish to censor / remove your UDID from the logs you have attached above. I see a lot of people avoiding showing their UDID, so I assume there must be a reason. I'm not sure exactly what the harm is of publicly showing UDID, but best be on the safe side.

**Comment by sai-tirunagiri** [comment]
Yes, Even I don't know what is the harm in displaying the UDID, I see from your commit to mask the UDID, that should fix the problem and my real problem right now is, the wda is still crashing.

I tried doing the xcodebuild from the terminal and I see no problem.
```
xcodebuild test-without-building -xctestrun /Users/blr-cauvery/Desktop/farmer/ios_remote_provider/bin/wda/WebDriverAgentRunner_iphoneos14.4-arm64-armv7.xctestrun -destination id=****13a67
```

Are there some pointers why it's not working from the provider?

**Comment by sai-tirunagiri** [comment]
@nanoscopic I was able to get the wda working now but, now when I click on the video option on UI, I am seeing the below error.

```
Created wda session id=7A9F2F4C-D49B-4CC4-804A-562033B83B03
Got connection to port
INFO[0015] Socket dial error                             err="read tcp 127.0.0.1:63362->127.0.0.1:8104: read: connection reset by peer" spec="tcp://127.0.0.1:8104" type=err_socket_dial
Got connection to port
INFO[0025] Socket dial error                             err="read tcp 127.0.0.1:63364->127.0.0.1:8104: read: connection reset by peer" spec="tcp://127.0.0.1:8104" type=err_socket_dial
Got connection to port
INFO[0035] Socket dial error                             err="read tcp 127.0.0.1:63365->127.0.0.1:8104: read: connection reset by peer" spec="tcp://127.0.0.1:8104" type=err_socket_dial
Got connection to port
INFO[0045] Socket dial error                             err="read tcp 127.0.0.1:63368->127.0.0.1:8104: read: connection reset by peer" spec="tcp://127.0.0.1:8104" type=err_socket_dial
Got connection to port
INFO[0055] Socket dial error                             err="read tcp 127.0.0.1:63377->127.0.0.1:8104: read: connection reset by peer" spec="tcp://127.0.0.1:8104" type=err_socket_dial
Got connection to port
INFO[0065] Socket dial error                             err="read tcp 127.0.0.1:63380->127.0.0.1:8104: read: connection reset by peer" spec="tcp://127.0.0.1:8104" type=err_socket_dial
Got request to start video stream for 5126be31cfff436356a1627c09c9268136513a67
Connecting to CF imgStream
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x4333769]

goroutine 89 [running]:
main.(*AppStream).setImageConsumer(0xc00066e1e0, 0xc000118600)
	/Users/saiprasadt/Desktop/farmer/ios_remote_provider/video_stream.go:70 +0x89
main.(*Device).startStream(0xc000676120, 0xc000156160)
	/Users/saiprasadt/Desktop/farmer/ios_remote_provider/device.go:231 +0x1b1
main.(*ControlFloor).startStream(0xc00007c600, 0xc00002c120, 0x28)
	/Users/saiprasadt/Desktop/farmer/ios_remote_provider/controlfloor.go:129 +0x26d
main.(*ControlFloor).openWebsocket.func2.4(0xc00007c600, 0xc00002c120, 0x28)
	/Users/saiprasadt/Desktop/farmer/ios_remote_provider/controlfloor.go:228 +0x3f
created by main.(*ControlFloor).openWebsocket.func2
	/Users/saiprasadt/Desktop/farmer/ios_remote_provider/controlfloor.go:228 +0x3e5
```

**Comment by sai-tirunagiri** [comment]
I am sure I have done the manual steps mentioned on this post - #https://github.com/nanoscopic/ios_remote_provider/issues/1#issuecomment-779640433 Still no luck, I am seeing the same error as posted above.

**Comment by nanoscopic** [comment]
@sai-tirunagiri The error you are showing is simply due to the provider being unable to connect to the controlsocket of the app for video. This is likely a result of starting/restarting everything repeatedly and having hanging iosif processes.

Generally, as I think I already said though, you can do the following:
0. Stop the provider process you are running
1. `killall iosif`
2. Stop recording through control center on your device. Start it again.
3. Start provider again
4. Ensure you see "Tunnel from 8103 to 8352 -> bound to port 8103" and the equivalent for port 8104 near the beginning of the output of the provider. If you don't; you will have issues / it won't work.

I need to add more error checking with clean output errors. Many of the errors you and others are showing are simply the result of leftover processes and inability to bind to ports etc.

There are of course a variety of problems that I have been fixing as well... I can only continue to improve the error checking and checks to try to avoid the problems.

**Comment by nanoscopic** [comment]
@sai-tirunagiri I've also updated the repo now to fix the process shutdown/cleanup. Now on startup leftover iosif processes will actually be killed automatically, so you don't need to worry any more about those.

**Comment by sai-tirunagiri** [comment]
@nanoscopic I managed to get it working! The other question what I had is, I tried interacting with one of the app using the keyboard but seems like it's not working and on the device, the keyboard is displayed but wherein on the controlfloor UI, the keyboard is not visible. Any suggestions ?

**Comment by sai-tirunagiri** [comment]
@nanoscopic Do you have some pointers on getting the keyboard interaction working?

**Comment by sai-tirunagiri** [comment]
I have implemented the above feature, I will raise a PR for it in the next 2 days after I run some tests.
