### ISSUE TITLE
Fail to communicate with controlfloor

### ISSUE THREAD

**Issue by sai-tirunagiri** [nanoscopic/ios_remote_provider#30]
Hi,

the ios remote provider breaks intermittently while communicating a message back to controlfloor. In this case what should be the workaround.

```
goroutine 34 [running]:
main.(*ControlFloor).baseNotify(0xc0002a4480, 0x43b09fc, 0xe, 0xc0004da1b0, 0x28, 0xc000673700)
	/Users/macmini1_df_uk/Documents/ios_remote_provider/controlfloor.go:377 +0x32c
main.(*ControlFloor).notifyProvisionStopped(...)
	/Users/macmini1_df_uk/Documents/ios_remote_provider/controlfloor.go:421
main.(*DeviceTracker).shutdown(0xc0002cac40)
	/Users/macmini1_df_uk/Documents/ios_remote_provider/device_tracker.go:160 +0x43b
main.coro_sigterm.func1(0xc000068e40, 0xc0002cac40, 0xc00011a000)
	/Users/macmini1_df_uk/Documents/ios_remote_provider/shutdown.go:26 +0x1f6
created by main.coro_sigterm
	/Users/macmini1_df_uk/Documents/ios_remote_provider/shutdown.go:19 +0xdc
panic: Post "https://SOMEDNS/provider/devStatus": dial tcp: lookup SOMEDNS: no such host
```
Thanks

**Comment by Immanuel-GWU** [comment]
So @sai-tirunagiri have you found out how to solve this issue. I too face this. Once I see the phone screen and perform a swipe action. In 20 seconds I'm not able to perform any actions because the same log that you see I see too. The control floor gets stuck.
I think @nanoscopic is not working on this project anymore, seeing many unanswered questions.
