### ISSUE TITLE
long run remote_provider error

### ISSUE THREAD

**Issue by s4ib0t87** [nanoscopic/ios_remote_provider#62]
Hi nanoscopic,

at our environment CF and one device connected via remote_provider run 24/7. The following error occurs if the remote_provider is connected more then 24 hours to CF.

remote_provider is running, receiving ping packets from CF and answering them. 
ImgStream via CF is requested to remote_provider. 
remote_provider connects to CF imgStream
remote_provider breaks with the following message: panic: websocket: bad handshake

logs:

CF
```
Reserving device ***401E for ok
time="2021-09-28T10:52:58+02:00" level=info msg="Image stream connected" rid=cEKYWqaQvg type=imgstream_start udid="***401E"
sending startStream to provider
sending {id:0,type:"startStream",udid:"***401E"}

provider fail
received
time="2021-09-28T10:53:04+02:00" level=info msg="Deleting device reservation" rid=cEKYWqaQvg type=reserve_delete udid="***401E"
dev video stopped for udid: ***401E
```

remote_provider
```
Got request to start video stream for ***401E
Connecting to CF imgStream
panic: websocket: bad handshake

goroutine 182 [running]:
main.(*ControlFloor).connectVidChannel(0xc0000a8000, 0xc000022220, 0x19, 0x19)
	/opt/ios_remote_provider/controlfloor.go:174 +0x370
main.(*Device).startVidStream(0xc0001c1340)
	/opt/ios_remote_provider/device.go:466 +0x47
main.(*ControlFloor).startVidStream(...)
	/opt/ios_remote_provider/controlfloor.go:151
main.(*ControlFloor).openWebsocket.func8(0xc0000a8000, 0xc00009c280, 0x19)
	/opt/ios_remote_provider/controlfloor.go:327 +0x65
created by main.(*ControlFloor).openWebsocket
	/opt/ios_remote_provider/controlfloor.go:327 +0x949
```

If you need more information please contact me, I can also provide pcap files from both sides. 

Thank in advance

**Comment by nanoscopic** [comment]
The video app broadcast stream periodically crashes for no apparent reason. In order to address this the latest changes detect that and automatically restart the broadcast stream.

Please update to the latest provider code and you should find that this issue has already been fixed.

**Comment by s4ib0t87** [comment]
Hi,
I just was now able to reproduce the issue on the latest version (updated at first October)

since the logs did change a bit here are the now logs. 

CF

```
uauth
checking for ok
user fail
login ok; user=ok
Reserving device ***401E for ok
time="2021-10-04T08:44:32+02:00" level=info msg="Image stream connected" rid=vqtusJSFSC type=imgstream_start udid="***401E"
      Response from browser: {"clientTime":"1633329871694","sentTime":"1633329872690"}
Client time:1633329871694
Milliseconds to client:17
Client Offset:1013
sending startStream to provider
sending {id:0,type:"startStream",udid:"00008101-0013443C3881401E"}

provider fail
received
dev video stopped for udid: ***401E
time="2021-10-04T08:44:36+02:00" level=info msg="Deleting device reservation" rid=vqtusJSFSC type=reserve_delete udid="***401E"
```

remote_provider

```
INFO Video handler start                           type=video_handler_start udid="***401E"
Got request to start video stream for ***401E
Connecting to CF imgStream
panic: websocket: bad handshake

goroutine 355394 [running]:
main.(*ControlFloor).connectVidChannel(0xc0001d0100, 0xc0002bc060, 0x19, 0x19)
	/opt/ios_remote_provider/controlfloor.go:176 +0x370
main.(*Device).startVidStream(0xc0001f8b00)
	/opt/ios_remote_provider/device.go:481 +0x47
main.(*ControlFloor).startVidStream(...)
	/opt/ios_remote_provider/controlfloor.go:153
main.(*ControlFloor).openWebsocket.func9(0xc0001d0100, 0xc000022f00, 0x19)
	/opt/ios_remote_provider/controlfloor.go:339 +0x65
created by main.(*ControlFloor).openWebsocket
	/opt/ios_remote_provider/controlfloor.go:339 +0x969
```

KR
