### ISSUE TITLE
Debugging CF http registration failure

### ISSUE THREAD

**Issue by mcloudfarm** [nanoscopic/ios_remote_provider#65]
mcloud@Mac-mini-Valeria ios_remote_provider % ./main register
Enter registration password:
Using default registration password of doreg
panic: JSON Incomplete

goroutine 1 [running]:
github.com/nanoscopic/ujsonin/v2/mod.Parse(0xc0000b0000, 0x12, 0x200, 0x12, 0x200, 0x0, 0x0, 0x44743fb)
 /Users/mcloud/go/pkg/mod/github.com/nanoscopic/ujsonin/v2@v2.0.6/mod/ujsonin.go:428 +0xc5
main.doregister(0xc00011f380, 0x0, 0x0)
 /Users/mcloud/ios_remote_provider/controlfloor.go:670 +0x579
main.runRegister(0xc000140320)
 /Users/mcloud/ios_remote_provider/main.go:420 +0x39
github.com/nanoscopic/uclop/mod.(*Cmd).Run(...)
 /Users/mcloud/go/pkg/mod/github.com/nanoscopic/uclop@v1.1.0/mod/main.go:164
github.com/nanoscopic/uclop/mod.(*Uclop).Run(0xc00018be30)
 /Users/mcloud/go/pkg/mod/github.com/nanoscopic/uclop@v1.1.0/mod/main.go:159 +0x262
main.main()
 /Users/mcloud/ios_remote_provider/main.go:76 +0xded
mcloud@Mac-mini-Valeria ios_remote_provider %

**config.json**

{
    controlfloor: {
        host: "localhost:8080"
        username: "first"
        https: true
        selfSigned: true
    }
    cfa: {
            // Your Apple Developer Team OU
            // If you don't know this, you can find it by running ./util/signers.pl
            devTeamOu: "XXXXXXXX"
            
            // Some unique Bundle ID prefix to usefor the Bundle IDs for CFAgent
            // This default, "com.dryark", will likely work for paid developer accounts
            // Make sure the provisioning profile you setup has a wildcard identifier matching this
            // The two identifiers that will be made if "com.dryark" is used are
            // "com.dryark.CFAgentLib"
            // "com.dryark.CFAgent"
            // If you are using a free developer account, you will not have any provisioning profile,
            //   so you will need to set this bundle prefix to something globally unique, such as
            //   "com.[your name]"
            bundleIdPrefix: "com.dryark"
            
            runner: {
                buildStyle: "Automatic" // or "Manual"
                provisioningProfile: "" // specify when buildStyle is Manual
            }
    },
    wda: {
        // Your Apple Developer Team OU
        // If you don't know this, you can find it by running ./util/signers.pl
        devTeamOu: "XXXXXXXX"
        
        // Some unique Bundle ID prefix to usefor the Bundle IDs for WebDriverAgent
        // This default, "com.appium", will likely work for paid developer accounts
        // Make sure the provisioning profile you setup has a wildcard identifier matching this
        // The two identifiers that will be made if "com.appium" is used are
        // "com.appium.WebDriverAgentLib"
        // "com.appium.WebDriverAgentRunner"
        // If you are using a free developer account, you will not have any provisioning profile,
        //   so you will need to set this bundle prefix to something globally unique, such as
        //   "com.[your name]"
        bundleIdPrefix: "com.appium"
        
        runner: {
            buildStyle: "Automatic" // or "Manual"
            provisioningProfile: "" // specify when buildStyle is Manual
        }
        
        startMethod: "tidevice"
    },
    vidapp: {
        devTeamOu: "XXXXXXXX"
        bundleIdPrefix: "com.appium"
    },
    devices: [
        {
            udid:"c1fdd587a8a71baa208650daee9951ddc5e1003d"
            uiWidth:375
            uiHeight:667
            controlCenterMethod: "topDown"
        },
        {
            udid:"ebae5996691577635130b1900ebf4b261ac5ec18"
            uiWidth:375
            uiHeight:667
            controlCenterMethod: "topDown"
        },
        {
            udid:"00008030-001454190EEB802E"
            uiWidth:375
            uiHeight:667
            controlCenterMethod: "topDown"
        },
        {
            udid:"00008101-00125D080112001E"
            uiWidth:375
            uiHeight:812
            controlCenterMethod: "topDown"
        },
        {
            udid:"70df7dabfb451d77c1f061b3ee2f0729a4fcb3af"
            uiWidth:768
            uiHeight:1024
            controlCenterMethod: "topDown"
        }
    ]
}

**Comment by mcloudfarm** [comment]
thanks, there was a 404 error!
