### ISSUE TITLE
ios remote provider run command 

### ISSUE THREAD

**Issue by jagdish24** [nanoscopic/ios_remote_provider#70]
After entering below commands, 
```
make
 make wda 
./main register 

```

Also here is log from ./main register

```
 ios_remote_provider % ./main register
WARN Could not read specified calculated path. Calculated options will not function.  defaults_path=calculated.json error="stat calculated.json: no such file or directory" type=err_read_calculated
Enter registration password:
panic: Post "https://localhost:8080/provider/register": dial tcp [::1]:8080: connect: connection refused

goroutine 1 [running]:
main.doregister(0xc0001211e0, 0x0, 0x0)
	/Users/-/CF_Setup/ios_remote_provider/ios_remote_provider/controlfloor.go:766 +0x993
main.runRegister(0xc00010e370)
	/Users/-/CF_Setup/ios_remote_provider/ios_remote_provider/main.go:621 +0x39
github.com/nanoscopic/uclop/mod.(*Cmd).Run(...)
	/Users/-/go/pkg/mod/github.com/nanoscopic/uclop@v1.1.0/mod/main.go:164
github.com/nanoscopic/uclop/mod.(*Uclop).Run(0xc00018be40)
	/Users/-/go/pkg/mod/github.com/nanoscopic/uclop@v1.1.0/mod/main.go:159 +0x262
main.main()
	/Users/-/CF_Setup/ios_remote_provider/ios_remote_provider/main.go:101 +0x1465


```
run command gives me below errors,

```
ios_remote_provider % ./main run
WARN Could not read specified calculated path. Calculated options will not function.  defaults_path=calculated.json error="stat calculated.json: no such file or directory" type=err_read_calculated
FATA Could not read ControlFloor auth token. Have you run `./main register`?  config_path=cf.json error="stat cf.json: no such file or directory" type=err_read_config

```

**Comment by jagdish24** [comment]
Use this solution to get rid from register of cf.json warning or error, 

Use below command
`make usetidevice`

that's worked for me.

**Comment by Immanuel-Codoid** [comment]
Hi @jagdish24 can you share me your whole setup if possible or is there any other blog that can walk me through the steps for setup?. Currently I have now setup controlfloor alone and I can view its UI using the local host IP in my browser. I'm struggling with the next step
